baseURL = '/'
languageCode = 'en-us'
title = 'BinaryDigit'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

  # feather-icons: https://feathericons.com/

[menu]
  # [[menu.main]]
    # Unique identifier for a menu item
  # identifier = "posts"
  # url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
	# pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
  # post = ""

    # Display name
  #  name = "Updates"

    # Weights are used to determine the ordering
  # weight = 1


[[menu.main]]
    identifier = "blog"
    name = " Blog"
    url = "https://blog.binarydigit.io/"
    pre = "<span data-feather='book'></span>"
    weight = 1

[[menu.main]]
    identifier = "music"
    name = " Music"
    url = "/music/"
    pre = "<span data-feather='music'></span>"
    weight = 2

[[menu.main]]
    identifier = "pages"
    name = " Projects"
    url = "/projects/"
    pre = "<span data-feather='terminal'></span>"
    weight = 3

[[menu.main]]
    identifier = "now"
    name = " Now"
    url = "/now/"
    pre = "<span data-feather='clock'></span>"
    weight = 4

[[menu.main]]
    identifier = " rss"
    # name = " RSS"
    url = "https://binarydigit.io/index.xml"
    pre = "<span data-feather='rss'></span>"
    weight = 5

    #  [[menu.main]]
#    identifier = "tags"
#    name = " tags"
#    url = "/tags"
#    pre = "<span data-feather='tag'></span>"
#    weight = 6

# Can use /posts/index.xml

[params]
  # URL for the avatar on homepage
  avatarURL = "images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xs"

  # Description to display on homepage
  description = "tech, gaming, photography, streaming, music"

  # Social Icons on homepage
  socialIcons = [
      {name = "mastodon", url = "https://mstdn.games/@BinaryDigit"},
      {name = "microdotblog", url = "https://blog.binarydigit.io"},
      {name = "twitch", url = "https://www.twitch.tv/BinaryDigit"}, 
      {name = "soundcloud", url = "https://soundcloud.com/binarydigitio"},
      {name = "youtube", url = "https://youtube.com/BinaryDigit"},
      {name = "peertube", url = "https://makertube.net/a/BinaryDigit"},
      {name = "kofi", url = "https://ko-fi.com/binarydigit/"},
      {name = "email", url = "mailto:hello[at]binarydigit.io?subject=Hello from the website!"},
    ]

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#8be9fd"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet

  customHeadHTML = '''
    <link rel="stylesheet" type="text/css" href="../css/custom.css">
    <a rel="me" href="https://mstdn.games/@BinaryDigit"></a>
    <a rel="me" href="https://social.lol/@binarydigit"></a>
  '''

  customFooterHTML = '''
    <small>&copy BinaryDigit 2023</small>
  '''

  # Keywords relevant for SEO
  metaKeywords = ["blog", "binarydigit", "hugo"]

  # Footer text
  footer = "BinaryDigit"

[services]
  [services.rss]
    limit = 5

