baseURL = '/'
languageCode = 'en-us'
title = 'BinaryDigit'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

    # feather-icons: https://feathericons.com/

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
	pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Updates"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "pages"
    name = " Projects"
    url = "/projects/"
    pre = "<span data-feather='book'></span>"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = " tags"
    url = "/tags"
    pre = "<span data-feather='tag'></span>"
    weight = 3

[[menu.main]]
    identifier = "coffee"
    url = "https://ko-fi.com/binarydigit/"
    pre = "<span data-feather='coffee'></span>"
    weight = 4

[[menu.main]]
    identifier = "rss"
    url = "https://binarydigit.io/feed.xml"
    pre = "<span data-feather='rss'></span>"
    weight = 5


[params]
  # URL for the avatar on homepage
  avatarURL = "images/ghostie.gif"
  # avatarURL = "images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xs"

  # Description to display on homepage
  description = "Testing out Hugo!"

  # Social Icons on homepage
  socialIcons = [
      {name = "mastodon", url = "https://mstdn.games/@BinaryDigit"},
      {name = "soundcloud", url = "https://soundcloud.com/binarydigitio"},
      {name = "youtube", url = "https://youtube.com/BinaryDigit"},
      {name = "kofi", url = "https://ko-fi.com/BinaryDigit"},
    ]

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # Footer text
  footer = "BinaryDigit"
